name: brasilapi-v quality code CI

concurrency:
  group: ci-${{ github.event.number }}
  cancel-in-progress: true

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  fmt-check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-lastest

    steps:
      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: V doctor
        run: v doctor

      - name: Install brasilapi
        run: |
          v install ldedev.brasilapi

      - name: Move brasilapi source code to path start
        run: mv ~/.vmodules/ldedev/brasilapi ~/brasilapi

      - name: Verify Fmt
        run: v fmt -verify ~/brasilapi

  run-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-lastest

    steps:
      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: V doctor
        run: v doctor

      - name: Install brasilapi
        run: |
          v install ldedev.brasilapi

      - name: Move brasilapi source code to path start
        run: mv ~/.vmodules/ldedev/brasilapi ~/brasilapi

      - name: Execute Tests using Pure V Backend
        run: v -stats test ~/brasilapi
